//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhsAPP {
    
    public partial class daftarUjianKPWebUI {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lbStatusKP;
        protected System.Web.UI.WebControls.Label lblStatusTA;
        protected System.Web.UI.WebControls.Label lblStatusAsdos;
        protected System.Web.UI.WebControls.Panel Panel2;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.Label Label7;
        protected System.Web.UI.WebControls.TextBox txtNamaMhsWKP;
        protected System.Web.UI.WebControls.TextBox txtNPMWKP;
        protected System.Web.UI.WebControls.TextBox txtProdiWKP;
        protected System.Web.UI.WebControls.TextBox txthpmhsWKP;
        protected System.Web.UI.WebControls.Panel Panel3;
        protected System.Web.UI.WebControls.Label Label6;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.Label Label8;
        protected System.Web.UI.WebControls.Label Label9;
        protected System.Web.UI.WebControls.Label Label14;
        protected System.Web.UI.WebControls.TextBox txtJudulKP;
        protected System.Web.UI.WebControls.TextBox txtNamaPer;
        protected System.Web.UI.WebControls.TextBox txtAlamatPer;
        protected System.Web.UI.WebControls.TextBox txtDosen;
        protected System.Web.UI.WebControls.Panel Panel4;
        protected System.Web.UI.WebControls.Label Label10;
        protected System.Web.UI.WebControls.Label Label11;
        protected System.Web.UI.WebControls.Label Label12;
        protected System.Web.UI.WebControls.Label Label13;
        protected System.Web.UI.WebControls.TextBox txtTgl;
        protected System.Web.UI.WebControls.DropDownList dropWaktu;
        protected System.Web.UI.WebControls.TextBox txtFasilitas;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
    }
}
