//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhsAPP {
    
    public partial class printDaftarTAWebUI {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lbStatusKP;
        protected System.Web.UI.WebControls.Label lblStatusTA;
        protected System.Web.UI.WebControls.Label lblStatusAsdos;
        protected CrystalDecisions.Web.CrystalReportViewer CrystalReportViewer1;
    }
}
