//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhsAPP {
    
    public partial class daftarTAWebUI {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lbStatusKP;
        protected System.Web.UI.WebControls.Label lblStatusTA;
        protected System.Web.UI.WebControls.Label lblStatusAsdos;
        protected System.Web.UI.WebControls.Panel Panel2;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.TextBox txtNamaMhsWTA;
        protected System.Web.UI.WebControls.TextBox txtNPMWTA;
        protected System.Web.UI.WebControls.TextBox txtProdiWTA;
        protected System.Web.UI.WebControls.Panel Panel3;
        protected System.Web.UI.WebControls.Label Label6;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.TextBox txtIPK;
        protected System.Web.UI.WebControls.Label Label7;
        protected System.Web.UI.WebControls.TextBox txtKonsentrasi;
        protected System.Web.UI.WebControls.TextBox txtmakul1;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected System.Web.UI.WebControls.TextBox txtnilaimk1;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator8;
        protected System.Web.UI.WebControls.TextBox txtmakul2;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
        protected System.Web.UI.WebControls.TextBox txtnilaimk2;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator9;
        protected System.Web.UI.WebControls.TextBox txtmakul3;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
        protected System.Web.UI.WebControls.TextBox txtnilaimk3;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator10;
        protected System.Web.UI.WebControls.TextBox txtmakul4;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
        protected System.Web.UI.WebControls.TextBox txtnilaimk4;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator11;
        protected System.Web.UI.WebControls.TextBox txtmakul5;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;
        protected System.Web.UI.WebControls.TextBox txtnilaimk5;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator12;
        protected System.Web.UI.WebControls.Panel Panel1;
        protected System.Web.UI.WebControls.Label Label8;
        protected System.Web.UI.WebControls.TextBox txtTopik1;
        protected System.Web.UI.WebControls.DropDownList dp11;
        protected System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
        protected System.Web.UI.WebControls.DropDownList dp21;
        protected System.Web.UI.WebControls.TextBox txtTopik2;
        protected System.Web.UI.WebControls.DropDownList dp12;
        protected System.Web.UI.WebControls.DropDownList dp22;
        protected System.Web.UI.WebControls.TextBox txtTopik3;
        protected System.Web.UI.WebControls.DropDownList dp13;
        protected System.Web.UI.WebControls.DropDownList dp23;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.Label idProd;
    }
}
