//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mhsAPP {
    
    public partial class KPWebUI {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lbStatusKP;
        protected System.Web.UI.WebControls.Label lblStatusTA;
        protected System.Web.UI.WebControls.Label lblStatusAsdos;
        protected System.Web.UI.WebControls.Panel Panel1;
        protected System.Web.UI.WebControls.Button btndaftarKP;
        protected System.Web.UI.WebControls.Button btndftrujKP;
        protected System.Web.UI.WebControls.Panel Panel2;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Label Label4;
        protected System.Web.UI.WebControls.Label Label5;
        protected System.Web.UI.WebControls.Label Label7;
        protected System.Web.UI.WebControls.TextBox txtNamaMhsWKP;
        protected System.Web.UI.WebControls.TextBox txtNPMWKP;
        protected System.Web.UI.WebControls.TextBox txtProdiWKP;
        protected System.Web.UI.WebControls.TextBox txtEmailWKP;
        protected System.Web.UI.WebControls.TextBox txthpmhsWKP;
        protected System.Web.UI.WebControls.Button btnEditEmail;
        protected System.Web.UI.WebControls.Button btnEdHpWKP;
    }
}
